server:
  port: 3000

db:
  postgres:
    type: 'postgres'
    port: 5432
    database: 'viriciti'
  mongo:
    type: 'mongo'
    host: 'localhost'
    port: 27017
    username: 'viriciti'
    password: 'viriciti'
    settings:
      useUnifiedTopology: true
      connectTimeoutMS: 5000
      socketTimeoutMS: 5000

rate-limiter:
  type: Memory
  points: 100
  duration: 60
  keyPrefix: global

jwt:
  expiresIn: 3600
