db:
  postgres:
    host: localhost
    username: 'viriciti'
    password: 'viriciti'
    synchronize: true

  mongo:
    host: 'localhost'
    username: 'viriciti'
    password: 'viriciti'

jwt:
  secret: 'viriciti'
