version: '2.4'

services:

  postgres:
    image: postgres:9.6.2-alpine
    container_name: 'postgres_db'
    environment:
      POSTGRES_USER: viriciti
      POSTGRES_PASSWORD: viriciti
      POSTGRES_DB: viriciti
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "viriciti"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./data/db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - viriciti-network

  mongo:
    image: mongo:latest
    container_name: 'mongo_db'
    environment:
      MONGO_INITDB_DATABASE: viriciti
      MONGO_INITDB_ROOT_USERNAME: viriciti
      MONGO_INITDB_ROOT_PASSWORD: viriciti
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - viriciti-network

  mongo-test:
    image: mongo:latest
    container_name: 'mongo_test_db'
    environment:
      NODE_ENV: development
      MONGO_INITDB_DATABASE: viriciti-test
      MONGO_INITDB_ROOT_USERNAME: viriciti-test
      MONGO_INITDB_ROOT_PASSWORD: viriciti-test
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./data/db/mongo-test:/data/db
    ports:
      - "27018:27017"
    networks:
      - viriciti-network

  redis:
    image: bitnami/redis:latest
    container_name: 'redis_cache'
    environment:
      REDIS_PASSWORD: 'viriciti'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - viriciti-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: 'backend_nestjs'
    healthcheck:
      test: ["CMD", "wget", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - viriciti-network

networks:
  viriciti-network:
